/* orders.cpp
 *
 * Justin Greever
 * CS202 - Program #1
 * 01/09/2020
 * 
 * //TODO: Add comments
 */

#include "orders.hpp"
using namespace std;

//This is the default constructor, initialize everything to NULL or 0
orders::orders(): order_id(0), customer_name(NULL), customer_address(NULL), shipping_type(NULL)
{
    //Nothing to do here! Done in the initialization list above
}

//Destructor since we will be using dynamic memory
orders::~orders()
{
    order_id = 0;
    if (customer_name)
        delete []customer_name;
    if (customer_address)
        delete []customer_address;
    if (shipping_type)
        delete []shipping_type;
    customer_name = customer_address = shipping_type = NULL;
}

//Add a new order. This will accept the following arguments:
//char *customer_name, char *customer_address, char *shipping_type
//Order ID will be autogenerated within this function (most likely
//incremental)
void orders::new_order()
{

}

void orders::edit_order()
{

}

void orders::cancel_order()
{

}
